
build:
  version: "3.0"
loans:
  message: "Welcome to Bank Loans related APIs "
  contactDetails:
    name: "RaviKumar - Product Owner"
    email: "RaviKumar@bank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384

