spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related QA APIs "
  contactDetails:
    name: "Smith Ray - QA Lead"
    email: "smitha@bank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371