
server:
  port: 8080
spring:

  application:
    name: accounts
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:accountsdb}
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update # possible values: none, create, create-drop, update, validate
      show-sql: true # possible values: true, false
  config:
    import: optional:configserver:http://localhost:8071
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
