spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to Bank cards related QA APIs "
  contactDetails:
    name: "Pankaj - QA Lead"
    email: "Pankaj@bank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267